language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose pylint
  # TODO: add specific version
  - pip install errbot
# command to run tests
script:
  - find . -name "*.py" | xargs pylint -E
